name: heads_web
dependencies:
- astropy=1.0.4=np19py27_0
- flask=0.10.1=py27_1
- gunicorn=19.1.0=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_0
- markupsafe=0.23=py27_0
- numpy=1.10=py27_0
- openssl=1.0.1k=1
- pastedeploy=1.5.2=py27_1
- pip=7.1.0=py27_1
- python=2.7.10=0
- readline=6.2=2
- setuptools=18.1=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- werkzeug=0.10.4=py27_0
- wheel=0.24.0=py27_0
- zlib=1.2.8=0
- pip:
  - dominate==2.1.12
  - flask-bootstrap==3.3.5.6

